version: '3'

services:
    front-end:
        restart: "unless-stopped"
        container_name: "dash-file-manager"
        build: 
            context: 'front/'
            dockerfile: 'docker/Dockerfile'
        command: 'python src/fronty.py'
        environment:
            DATA_DIR: "${PWD}/data/"
        volumes:
            - "./data:/app/work/data"
            - "./front/src:/app/work/src"
        ports:
            - '8060:8060'