version: '3'

services:
    front-end:
        container_name: "file-manager"
        build: .
        environment:
            DEFAULT_TILED_URI: "${DEFAULT_TILED_URI}"
            DEFAULT_TILED_SUB_URI: "${DEFAULT_TILED_SUB_URI}"
            TILED_KEY: "${TILED_KEY}"
            DATA_DIR: "/app/work/data"
        volumes:
            - "${DATA_DIR}:/app/work/data"
        ports:
            - '127.0.0.1:8050:8050'
