version: '3'

services:
    front-end:
        restart: "unless-stopped"
        container_name: "dash-file-manager"
        build:
            context: '.'
            dockerfile: 'Dockerfile'
        environment:
            SPLASH_URL: "${SPLASH_URL}"
            TILED_KEY: "${TILED_KEY}"
        volumes:
            - "${DATA_DIR}:/app/work/data"
        ports:
            - '127.0.0.1:8050:8050'
